name: Template
model_controls_emotion: false
cpu_threshold: 90
ram_threshold: 90
offload_policy: log_only
disk_threshold_warn: 90
disk_threshold_critical: 95
prune_paths: []
network_policies:
  allow_ports: []
  block_ports: []
  max_bandwidth_percent: 90
  mode: monitor_only  # monitor_only | active_enforce
federation_peer_ip: null
