repos:
- repo: local
  hooks:
  - id: privilege-lint
    name: privilege lint
    entry: bash scripts/precommit_privilege.sh
    language: system
    pass_filenames: false
  - id: audit-verify
    name: audit log verify
    entry: python verify_audits.py
    language: system
    pass_filenames: false
  - id: pytest
    name: unit tests
    entry: bash -c "pip install -e . && pytest -q"
    language: python
    additional_dependencies:
      - pytest
      - pytest-cov
      - requests
      - PyYAML
    pass_filenames: false
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.0
  hooks:
    - id: mypy
      additional_dependencies:
        - types-requests
        - types-PyYAML
        - requests
        - pytest-cov
        - PyYAML
