repos:
  - repo: local
    hooks:
      - id: privilege-lint
        name: privilege lint
        entry: bash -c 'LUMOS_AUTO_APPROVE=1 scripts/precommit_privilege.sh'
        language: system
        pass_filenames: false
      - id: audit-verify
        name: audit log verify
        entry: bash -c 'LUMOS_AUTO_APPROVE=1 python verify_audits.py logs/ --no-input'
        language: system
        pass_filenames: false
      - id: pytest
        name: unit tests
        entry: pytest --cov=sentientos --cov-fail-under=80 -q
        language: python
        pass_filenames: false
        additional_dependencies:
          - pytest
          - pytest-cov
          - requests
          - mypy
          - requests_mock
          - PyYAML
          - types-PyYAML
          - types-requests
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
