repos:
- repo: local
  hooks:
  - id: privilege-lint
    name: privilege lint
    entry: python privilege_lint.py --quiet
    language: system
    pass_filenames: false
  - id: audit-verify
    name: audit log verify
    entry: python verify_audits.py
    language: system
    pass_filenames: false
