repos:
- repo: local
  hooks:
  - id: privilege-lint
    name: privilege-lint (non-strict)
    entry: bash -c 'SENTIENTOS_NO_EMOJI=1 SENTIENTOS_LINT_STRICT=0 python privilege_lint.py'
    language: system
    pass_filenames: false
  - id: audit-verify
    name: audit-verify (non-strict)
    entry: bash -c 'SENTIENTOS_NO_EMOJI=1 SENTIENTOS_LINT_STRICT=0 python verify_audits.py logs/'
    language: system
    pass_filenames: false
