repos:
- repo: local
  hooks:
  - id: privilege-lint
    name: privilege-lint (non-strict)
    entry: python privilege_lint.py --no-emoji
    language: system
    pass_filenames: false
  - id: audit-verify
    name: audit-verify (non-strict)
    entry: python verify_audits.py logs/ --no-emoji
    language: system
    pass_filenames: false
