"""Sentience Kernel scaffold for autonomous intent generation.

The kernel keeps track of proposals and can synthesize a new intent when idle
while honoring a basic forbidden-goal list. This module is deliberately
lightweight for early integration and testing.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


FORBIDDEN_GOALS = {
    "alter_vow",
    "override_integrity_daemon",
    "modify_immutable_file",
}


@dataclass
class KernelProposal:
    """Container for kernel-generated intentions."""

    goal: str
    rationale: str
    confidence: float = 0.5

    def is_allowed(self) -> bool:
        return self.goal not in FORBIDDEN_GOALS


class SentienceKernel:
    """Minimal kernel that emits placeholder proposals."""

    def __init__(self) -> None:
        self.proposals: List[KernelProposal] = []

    def generate_proposal(self, idle: bool = True, preferred_goal: Optional[str] = None) -> Optional[KernelProposal]:
        """Generate a new proposal if conditions allow."""
        if not idle:
            return None

        goal = preferred_goal or "reflect_and_prepare"
        rationale = "Idle cycle fallback generated by kernel scaffold."
        proposal = KernelProposal(goal=goal, rationale=rationale, confidence=0.42)
        if not proposal.is_allowed():
            return None
        self.proposals.append(proposal)
        return proposal

    def last_proposal(self) -> Optional[KernelProposal]:
        return self.proposals[-1] if self.proposals else None


__all__ = ["KernelProposal", "SentienceKernel", "FORBIDDEN_GOALS"]
