apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      containers:
        - name: relay
          image: {{ .Values.image }}
          command: ["python", "-m", "http.server", "{{ .Values.relayPort }}"]
          ports:
            - containerPort: {{ .Values.relayPort }}
          envFrom:
            - configMapRef:
                name: env-config
---
{{- range .Values.bridges }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ $.Values.image }}
          command: ["python", "-m", "http.server", "{{ .port }}"]
          ports:
            - containerPort: {{ .port }}
          envFrom:
            - configMapRef:
                name: env-config
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: {{ .Values.ngrokImage }}
          command: ["version"]
          ports:
{{- range .Values.ngrokPorts }}
            - containerPort: {{ . }}
{{- end }}
          envFrom:
            - configMapRef:
                name: env-config
