apiVersion: v1
kind: Service
metadata:
  name: relay
spec:
  selector:
    app: relay
  ports:
    - port: {{ .Values.relayPort }}
      targetPort: {{ .Values.relayPort }}
      name: http
---
{{- range .Values.bridges }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      name: http
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: ngrok
spec:
  selector:
    app: ngrok
  ports:
{{- range .Values.ngrokPorts }}
    - port: {{ . }}
      targetPort: {{ . }}
      name: port{{ . }}
{{- end }}
