from __future__ import annotations

from typing import Any


def orchestration_intent_fabric_note() -> dict[str, Any]:
    """Short technical note for constitutional judgment-to-execution handoff."""

    return {
        "layer": "orchestration_intent_fabric",
        "what_it_is": [
            "a bounded translation bridge from delegated judgment recommendations to typed orchestration intents",
            "a governed handoff substrate that stages execution intent without claiming sovereign execution authority",
        ],
        "how_it_differs_from_delegated_judgment": [
            "delegated judgment classifies and recommends; orchestration handoff emits typed intent/work-order artifacts",
            "delegated judgment stays recommendation_only; orchestration handoff is recommendation_only=false but still non_authoritative",
        ],
        "how_it_differs_from_execution": [
            "it does not execute external tools, browser, keyboard, or mouse actions",
            "it does not bypass task admission, kernel, or governor decisions",
            "it can hand internal_maintenance_execution intents into task_admission for bounded admission only",
            "handoff admission is not execution completion; execution remains downstream",
            "closed-loop orchestration result now resolves downstream task_executor task_result evidence for admitted internal handoffs",
        ],
        "internal_handoff_now_operational": {
            "intent_kind": "internal_maintenance_execution",
            "execution_target": "task_admission_executor",
            "admission_surface": "task_admission.admit",
            "handoff_outcomes": [
                "admitted_to_execution_substrate",
                "blocked_by_admission",
                "blocked_by_operator_requirement",
                "blocked_by_insufficient_context",
                "execution_target_unavailable",
                "staged_only",
            ],
        },
        "venue_to_executability": {
            "internal_direct_execution": "executable_now via task admission staging",
            "codex_implementation": "stageable_external_work_order",
            "deep_research_audit": "stageable_external_work_order",
            "operator_decision_required": "blocked_operator_required",
            "insufficient_context": "blocked_insufficient_context",
        },
        "proof_visible_artifact": "glow/orchestration/orchestration_intents.jsonl",
        "handoff_artifact": "glow/orchestration/orchestration_handoffs.jsonl",
        "handoff_packet_artifact": "glow/orchestration/orchestration_handoff_packets.jsonl",
        "fulfillment_receipt_artifact": "glow/orchestration/orchestration_fulfillment_receipts.jsonl",
        "codex_staged_work_order_artifact": "glow/orchestration/codex_work_orders.jsonl",
        "deep_research_staged_work_order_artifact": "glow/orchestration/deep_research_work_orders.jsonl",
        "handoff_packet_substrate": {
            "what_it_is": "a compact typed packet derived from next_move_proposal + delegated_judgment for operator/future-adapter pickup",
            "how_it_differs": {
                "from_delegated_judgment": "delegated judgment recommends venue/posture; packet binds that recommendation to a concrete venue-targeted handoff bundle",
                "from_next_venue_recommendation": "next-venue recommendation is directional; packet is a proof-visible, venue-specific actionable handoff object",
                "from_next_move_proposal": "next-move proposal frames posture/executability; packet packages compact brief, rationale, status, and evidence pointers",
            },
            "packetized_venues": [
                "task_admission_executor (internal_direct_execution path)",
                "codex_implementation",
                "deep_research_audit",
            ],
            "packet_status_meaning": {
                "prepared": "packet built but not trigger-ready",
                "blocked_operator_required": "operator/escalation gate blocks trigger",
                "blocked_insufficient_context": "context gap blocks honest trigger-readiness",
                "ready_for_external_trigger": "staged external packet ready for explicit operator/adapter trigger only",
                "ready_for_internal_trigger": "internal packet ready for existing admission trigger path only",
            },
            "explicitly_not": [
                "direct Codex/Deep Research invocation",
                "new execution or sovereign decision surface",
                "automatic routing/execution without existing admission and operator pathways",
            ],
        },
        "operator_feedback_repacketization": {
            "what_it_is": "bounded refresh synthesis that emits a new current handoff packet when valid operator resolution changes packetization-relevant state.",
            "eligible_resolution_kinds": [
                "approved_continue",
                "approved_with_constraints",
                "supplied_missing_context",
                "redirected_venue",
            ],
            "non_refresh_resolution_kinds": [
                "declined",
                "cancelled",
                "deferred",
            ],
            "lineage_shape": [
                "packet_lineage.supersedes_handoff_packet_id",
                "packet_lineage.superseded_by_handoff_packet_id (resolved from append-only history)",
                "packet_lineage.refresh_reason",
                "packet_lineage.source_operator_resolution_receipt_id",
                "packet_lineage.current_packet_candidate",
            ],
            "active_packet_surface": "sentientos.orchestration_intent_fabric.resolve_active_handoff_packet_candidate",
            "what_it_does_not_do": [
                "does not directly execute internal or external work",
                "does not bypass packetization gate",
                "does not override admission or operator authority boundaries",
                "does not erase held history; original packet remains inspectable",
            ],
        },
        "fulfillment_receipt_substrate": {
            "what_it_is": "a compact typed ingestion record for externally reported outcomes of staged handoff packets",
            "how_it_differs_from_handoff_packet": "handoff packet stages work intent; fulfillment receipt records externally supplied outcome evidence after staging",
            "fulfillment_kinds": [
                "externally_completed",
                "externally_completed_with_issues",
                "externally_declined",
                "externally_abandoned",
                "externally_result_unusable",
            ],
            "fulfilled_externally_means": "an external actor/operator reported an outcome and the receipt was appended to the proof-visible ledger",
            "fulfilled_externally_does_not_mean": [
                "direct in-repo Codex/Deep Research execution occurred",
                "automatic correctness approval of the external result",
                "sovereign authority transfer into this repository",
            ],
            "still_missing_before_direct_external_delegation": [
                "approved direct adapter invocation path",
                "strong external attestation/verification policy beyond receipt ingestion",
            ],
        },
        "codex_staged_venue_onboarding": {
            "status": "first_class_bounded_staged_venue",
            "venue": "codex_implementation",
            "constitutional_fields": [
                "work_order_id",
                "source_intent_id",
                "source_judgment_linkage",
                "operator_requirements",
                "executability_classification",
                "staged_only",
                "does_not_invoke_codex_directly",
                "requires_external_tool_or_operator_trigger",
                "non_authoritative",
                "decision_power=none",
            ],
            "lifecycle_states": [
                "staged_cleanly",
                "blocked_operator_required",
                "blocked_insufficient_context",
                "fulfilled_externally",
                "fulfilled_externally_with_issues",
                "externally_declined",
                "externally_abandoned",
                "fragmented_unlinked_work_order_state",
            ],
            "still_missing_before_any_direct_codex_delegation": [
                "an approved external transport/trigger path",
                "admission parity for external execution",
                "result attestation proving fulfillment beyond staged state",
            ],
            "still_out_of_scope": [
                "direct Codex invocation from this repository",
                "browser or desktop automation",
                "automatic completion claims without proof-visible external evidence",
            ],
        },
        "deep_research_staged_venue_onboarding": {
            "status": "first_class_bounded_staged_venue",
            "venue": "deep_research_audit",
            "constitutional_fields": [
                "work_order_id",
                "source_intent_id",
                "source_judgment_linkage",
                "operator_requirements",
                "executability_classification",
                "staged_only",
                "does_not_invoke_deep_research_directly",
                "requires_external_tool_or_operator_trigger",
                "non_authoritative",
                "decision_power=none",
            ],
            "lifecycle_states": [
                "staged_cleanly",
                "blocked_operator_required",
                "blocked_insufficient_context",
                "fulfilled_externally",
                "fulfilled_externally_with_issues",
                "externally_declined",
                "externally_abandoned",
                "fragmented_unlinked_work_order_state",
            ],
            "still_missing_before_any_direct_deep_research_delegation": [
                "an approved external transport/trigger path",
                "admission parity for external execution",
                "result attestation proving fulfillment beyond staged state",
            ],
            "comparison_to_codex_staged_venue": [
                "both venues are stageable_external_work_order only in this pass",
                "both venues carry stable work_order_id + source intent/judgment linkage",
                "both venues expose append-only proof artifacts and staged lifecycle visibility",
                "both venues remain non-sovereign and non-executable here",
            ],
            "still_out_of_scope": [
                "direct Deep Research invocation from this repository",
                "browser or desktop automation",
                "automatic completion claims without proof-visible external evidence",
            ],
        },
        "result_resolution": {
            "path": "internal_maintenance_execution -> task_admission_executor -> logs/task_executor.jsonl task_result",
            "result_states": [
                "handoff_admitted_pending_result",
                "execution_still_pending",
                "execution_succeeded",
                "execution_failed",
                "execution_result_missing",
                "handoff_not_admitted",
            ],
            "meaning": "handoff admission records substrate entry; orchestration result closure requires downstream task_result evidence.",
        },
        "unified_orchestration_result": {
            "what_it_is": "a bounded venue-aware resolver surface that normalizes internal execution closure and external fulfillment closure into one typed result shape",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_unified_orchestration_result",
            "inspectable_window_surface": "sentientos.orchestration_intent_fabric.resolve_unified_orchestration_result_surface",
            "split_closure_audit_surface": "sentientos.orchestration_intent_fabric.build_split_closure_map",
            "resolution_paths": ["internal_execution", "external_fulfillment"],
            "result_classifications": [
                "completed_successfully",
                "completed_with_issues",
                "declined_or_abandoned",
                "failed_after_execution",
                "blocked_before_execution",
                "pending_or_unresolved",
                "fragmented_result_history",
            ],
            "venue_honesty": [
                "external_fulfillment remains explicitly receipt-based and does_not_imply_direct_repo_execution",
                "internal_execution remains explicitly task_result-observed when complete",
                "unification does not collapse fulfillment into fake direct execution success",
            ],
            "what_it_does_not_do": [
                "does not add direct external actuation",
                "does not add a new execution venue",
                "does not change admission authority",
                "does not create sovereign decision power",
            ],
        },
        "unified_result_quality_review": {
            "meaning": "bounded retrospective quality classification over recent unified orchestration results across internal and external resolution paths.",
            "machine_surface": "sentientos.orchestration_intent_fabric.derive_unified_result_quality_review",
            "reads_from_unified_surface_only": [
                "resolve_unified_orchestration_result_surface.result_classification_counts",
                "resolve_unified_orchestration_result_surface.resolution_path_counts",
                "resolve_unified_orchestration_result_surface.fragmented_linkage_count",
                "unified result anti-sovereignty metadata already present in that surface",
            ],
            "classifications": [
                "healthy_recent_results",
                "issues_heavy",
                "abandonment_or_decline_heavy",
                "fragmentation_heavy",
                "mixed_result_stress",
                "insufficient_history",
            ],
            "preserves_internal_external_honesty": [
                "uses one unified classification surface without forcing internal and external paths into fake equivalence",
                "reports internal_execution vs external_fulfillment path mix directly in the summary basis",
                "keeps external fulfillment explicitly receipt-based, not direct execution proof",
            ],
            "explicitly_not": [
                "a new truth source",
                "a new execution venue",
                "admission or execution authority",
                "direct external actuation",
                "a sovereign decision layer",
            ],
        },
        "outcome_review": {
            "meaning": "bounded retrospective classification over recent internal orchestration outcomes, now with linked external fulfillment receipt influence for staged external venues.",
            "reads_existing_artifacts_only": [
                "glow/orchestration/orchestration_intents.jsonl",
                "glow/orchestration/orchestration_handoffs.jsonl",
                "logs/task_executor.jsonl task_result linkage",
                "glow/orchestration/orchestration_handoff_packets.jsonl",
                "glow/orchestration/orchestration_fulfillment_receipts.jsonl",
            ],
            "classifications": [
                "clean_recent_orchestration",
                "handoff_block_heavy",
                "execution_failure_heavy",
                "pending_stall_pattern",
                "mixed_orchestration_stress",
                "insufficient_history",
            ],
            "explicitly_not": [
                "a new admission authority",
                "a governor/kernel override",
                "direct external actuation",
                "a new execution venue",
            ],
            "external_fulfillment_mapping": {
                "fulfilled_externally": "healthy support signal",
                "fulfilled_externally_with_issues": "stressed support signal",
                "externally_declined": "blocked external pressure signal",
                "externally_abandoned": "blocked external pressure signal",
                "externally_result_unusable": "failure-like external quality signal",
            },
        },
        "venue_mix_review": {
            "meaning": "bounded retrospective check of recent venue-selection mix (internal execution vs staged Codex vs staged Deep Research vs operator-heavy escalation states) with compact external fulfillment quality contribution.",
            "reads_existing_artifacts_only": [
                "glow/orchestration/orchestration_intents.jsonl",
                "glow/orchestration/orchestration_handoffs.jsonl",
                "glow/orchestration/codex_work_orders.jsonl",
                "glow/orchestration/deep_research_work_orders.jsonl",
                "glow/orchestration/orchestration_handoff_packets.jsonl",
                "glow/orchestration/orchestration_fulfillment_receipts.jsonl",
                "orchestration_result_resolution linkage surfaces",
            ],
            "classifications": [
                "balanced_recent_venue_mix",
                "internal_execution_heavy",
                "codex_heavy",
                "deep_research_heavy",
                "operator_escalation_heavy",
                "mixed_venue_stress",
                "insufficient_history",
            ],
            "explicitly_not": [
                "admission authority",
                "execution authority",
                "a new venue",
                "direct external actuation",
            ],
            "external_quality_bounding": [
                "healthy external fulfillment contribution",
                "stressed external fulfillment contribution",
                "venue-heavy plus poor-fulfillment stress indicator",
            ],
        },
        "next_venue_recommendation": {
            "what_changed_in_this_pass": [
                "uses bounded external fulfillment history from venue_mix_review.external_fulfillment_contribution",
                "can affirm delegated Codex/Deep Research when that venue has healthy repeated external fulfillment",
                "can nudge away or hold when delegated external venue has stressed/declined/abandoned/unusable recent outcomes",
            ],
            "safety_bounds": [
                "does_not_override_delegated_judgment remains true",
                "single bad receipt does not dominate; stress signals require repeated outcomes",
                "staged-only packets without receipts remain explicitly distinct from fulfilled outcomes",
            ],
            "still_not_direct_execution": [
                "no direct Codex/Deep Research actuation",
                "no browser/mouse/keyboard control",
                "no sovereign execution authority transfer",
            ],
            "still_missing_before_autonomous_external_delegation": [
                "approved direct external trigger/adapter pathway",
                "strong fulfillment attestation + verification policy with execution parity",
                "governed autonomous retry/escalation policy that remains non-sovereign",
            ],
        },
        "operator_attention_recommendation": {
            "meaning": "bounded diagnostic recommendation about what operator attention internal orchestration behavior likely needs.",
            "derived_from": [
                "orchestration_outcome_review.review_classification",
                "orchestration_outcome_review.condition_flags",
                "orchestration_outcome_review.recent_outcome_counts",
            ],
            "values": [
                "none",
                "observe",
                "inspect_handoff_blocks",
                "inspect_execution_failures",
                "inspect_pending_stall",
                "review_mixed_orchestration_stress",
                "insufficient_context",
            ],
            "explicitly_not": [
                "workflow automation authority",
                "admission policy mutation",
                "execution control",
                "a sovereign decision surface",
            ],
        },
        "orchestration_trust_confidence_posture": {
            "meaning": "compact diagnostic posture summarizing how trustworthy recent bounded orchestration behavior is for continued delegated bounded use.",
            "machine_surface": "sentientos.orchestration_intent_fabric.derive_orchestration_trust_confidence_posture",
            "derived_from_existing_review_signals_only": [
                "next_move_proposal_review",
                "orchestration_venue_mix_review",
                "orchestration_outcome_review",
                "unified_result_quality_review",
                "orchestration_operator_attention_recommendation",
            ],
            "values": [
                "trusted_for_bounded_use",
                "caution_required",
                "stressed_but_usable",
                "fragmented_or_unreliable",
                "insufficient_history",
            ],
            "summary_surface": [
                "contributing review classes",
                "primary pressure category (proposal/venue/result-quality/escalation/fragmentation)",
                "compact rationale",
                "diagnostic_only and non_authoritative boundaries",
            ],
            "explicitly_not": [
                "admission authority",
                "execution authority",
                "release-readiness override",
                "a sovereign planner",
                "direct external actuation",
            ],
        },
        "delegated_operation_readiness": {
            "meaning": "a compact bounded verdict stating whether the current orchestration loop appears fit for continued supervised delegated operation.",
            "machine_surface": "sentientos.orchestration_intent_fabric.derive_delegated_operation_readiness_verdict",
            "derived_from_existing_review_signals_only": [
                "orchestration_trust_confidence_posture",
                "proposal_packet_continuity_review",
                "unified_result_quality_review",
                "orchestration_outcome_review",
                "orchestration_venue_mix_review",
                "next_move_proposal_review",
                "orchestration_operator_attention_recommendation",
                "packetization_gate_outcome",
                "active_handoff_packet_visibility",
            ],
            "values": [
                "ready_for_bounded_supervised_operation",
                "ready_with_caution",
                "operator_review_required",
                "temporarily_unfit_due_to_fragmentation",
                "insufficient_history",
            ],
            "how_it_differs_from_trust_confidence_posture": [
                "trust/confidence posture is one core signal; readiness verdict composes posture with packet continuity, packetization outcome, and current operator-attention pressure.",
                "readiness verdict adds compact dominant pressure and packetization/active-packet context for operational legibility.",
            ],
            "explicitly_not": [
                "admission authority",
                "execution authority",
                "a sovereign decision surface",
                "direct external actuation",
                "new venue routing",
            ],
        },
        "current_orchestration_watchpoint": {
            "meaning": "compact present-tense wake-condition object describing the specific next condition that would let bounded orchestration advance.",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_current_orchestration_watchpoint",
            "derived_from_current_state_surfaces_only": [
                "resolve_current_orchestration_state",
                "active_handoff_packet_visibility",
                "operator_action_brief_lifecycle",
                "packetization_gate",
                "unified_orchestration_result",
                "current proposal presence/absence",
            ],
            "watchpoint_classes": [
                "await_operator_resolution",
                "await_internal_execution_result",
                "await_external_fulfillment_receipt",
                "await_packetization_relief",
                "await_new_proposal",
                "no_watchpoint_needed",
            ],
            "how_it_differs": {
                "from_current_orchestration_state": "current state classifies what the loop is currently doing; watchpoint classifies what concrete event/artifact would let it advance next.",
                "from_delegated_operation_readiness": "readiness is a bounded fit verdict over retrospective + present signals; watchpoint is a narrow current-state wake dependency only.",
            },
            "explicitly_not": [
                "an event engine or scheduler",
                "execution/admission authority",
                "new venue routing",
                "direct external actuation",
                "a sovereign decision layer",
            ],
        },
        "current_orchestration_watchpoint_satisfaction": {
            "meaning": "bounded wake-readiness diagnostic indicating whether the active watchpoint wait condition is still pending, satisfied, stale, or fragmented.",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_watchpoint_satisfaction",
            "derived_from_existing_watchpoint_linked_surfaces_only": [
                "resolve_current_orchestration_watchpoint",
                "resolve_current_orchestration_state",
                "operator_action_brief_lifecycle",
                "unified_orchestration_result",
                "packetization_gate",
                "active_handoff_packet_visibility",
                "current proposal presence/absence",
            ],
            "statuses": [
                "watchpoint_pending",
                "watchpoint_satisfied",
                "watchpoint_stale",
                "watchpoint_fragmented",
                "no_active_watchpoint",
            ],
            "satisfying_signals": [
                "operator_resolution_receipt",
                "internal_execution_result",
                "external_fulfillment_receipt",
                "packetization_gate_relief_signal",
                "next_move_proposal",
            ],
            "how_it_differs": {
                "from_current_orchestration_state": "current state says what mode the loop is currently in; watchpoint satisfaction says whether the specific waited-for event is met yet.",
                "from_current_orchestration_watchpoint": "watchpoint defines what condition would wake the loop; watchpoint satisfaction reports present-tense status of that condition.",
            },
            "explicitly_not": [
                "scheduler behavior",
                "autonomous workflow execution",
                "admission or execution authority",
                "new venue routing",
                "a sovereign decision layer",
            ],
        },
        "re_evaluation_trigger_recommendation": {
            "meaning": "bounded re-entry recommendation that says how the loop should re-enter evaluation once watchpoint context is satisfied, stale, fragmented, or absent.",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_re_evaluation_trigger_recommendation",
            "derived_from_existing_current_state_watchpoint_surfaces_only": [
                "resolve_current_orchestration_state",
                "resolve_current_orchestration_watchpoint",
                "resolve_watchpoint_satisfaction",
                "operator_action_brief_lifecycle",
                "packetization_gate",
                "active_handoff_packet_visibility",
            ],
            "trigger_values": [
                "rerun_delegated_judgment",
                "rerun_packetization_gate",
                "rerun_packet_synthesis",
                "clear_wait_and_continue_current_packet",
                "hold_for_manual_review",
                "no_re_evaluation_needed",
            ],
            "how_it_differs": {
                "from_watchpoint_satisfaction": "watchpoint satisfaction says whether the wait condition is met; re-evaluation trigger recommendation says what bounded re-entry action is most conservative next.",
                "from_current_orchestration_watchpoint": "watchpoint defines the waited-for condition; re-evaluation trigger recommendation defines post-wake re-entry posture only.",
            },
            "explicitly_not": [
                "a scheduler or autonomous planner",
                "direct execution of recommended action",
                "admission authority",
                "execution authority",
                "new venue creation or routing",
            ],
        },
        "current_orchestration_resumption_candidate": {
            "meaning": "derived, non-executing current resume candidate that composes current state + watchpoint + watchpoint satisfaction + re-evaluation trigger into one bounded continuity posture.",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_current_orchestration_resumption_candidate",
            "derived_from_existing_watchpoint_and_re_entry_surfaces_only": [
                "resolve_current_orchestration_state",
                "resolve_current_orchestration_watchpoint",
                "resolve_watchpoint_satisfaction",
                "resolve_re_evaluation_trigger_recommendation",
                "resolve_active_handoff_packet_candidate",
                "resolve_operator_action_brief_lifecycle",
                "resolve_unified_orchestration_result",
                "derive_packetization_gate",
                "next_move_proposal_visibility",
            ],
            "bounded_resume_modes": [
                "rerun_delegated_judgment",
                "rerun_packetization_gate",
                "rerun_packet_synthesis",
                "clear_wait_and_continue_current_packet",
                "hold_for_manual_review",
                "no_re_evaluation_needed",
            ],
            "continuity_postures": [
                "continue_current_active_packet",
                "refresh_packet_from_current_proposal_state",
                "recompute_from_proposal_level_state",
                "none",
            ],
            "explicitly_not": [
                "a scheduler",
                "execution authority",
                "admission authority",
                "new orchestration venue",
                "new mutable truth source",
            ],
        },
        "current_orchestration_watchpoint_brief": {
            "meaning": "derived, non-executing compact brief that summarizes what current wait posture is active, what is being waited on, and what existing condition would satisfy/clear that wait.",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_current_orchestration_watchpoint_brief",
            "derived_from_existing_watchpoint_linked_surfaces_only": [
                "resolve_current_orchestration_state",
                "resolve_current_orchestration_watchpoint",
                "resolve_watchpoint_satisfaction",
                "resolve_re_evaluation_trigger_recommendation",
                "resolve_current_orchestration_resumption_candidate",
                "resolve_current_resumed_operation_readiness_verdict",
                "active_handoff_packet_visibility",
                "current proposal visibility",
                "operator resolution visibility",
                "unified result visibility",
            ],
            "wait_kinds": [
                "awaiting_external_fulfillment",
                "awaiting_operator_resolution",
                "awaiting_internal_result_closure",
                "continuity_uncertain",
                "no_active_watchpoint",
            ],
            "explicitly_not": [
                "a scheduler",
                "an execution engine",
                "a new orchestration layer",
                "an authority or control surface",
                "a new mutable truth source",
            ],
        },
        "current_orchestration_pressure_signal": {
            "meaning": "derived, non-executing current pressure classifier that compactly describes whether current orchestration appears stable, hold-shaped, redirect-shaped, repacketization-shaped, fragmented, mixed, or under-signaled.",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_current_orchestration_pressure_signal",
            "derived_from_existing_surfaces_only": [
                "resolve_current_orchestration_state",
                "resolve_current_orchestration_watchpoint",
                "resolve_watchpoint_satisfaction",
                "resolve_re_evaluation_trigger_recommendation",
                "resolve_current_orchestration_resumption_candidate",
                "resolve_current_resumed_operation_readiness_verdict",
                "resolve_current_orchestration_watchpoint_brief",
                "derive_proposal_packet_continuity_review",
                "active_handoff_packet_visibility",
                "current proposal visibility",
                "operator_resolution_influence",
                "unified_orchestration_result",
                "orchestration_trust_confidence_posture",
            ],
            "values": [
                "stable_or_low_pressure",
                "hold_pressure",
                "redirect_pressure",
                "repacketization_pressure",
                "fragmentation_pressure",
                "mixed_pressure",
                "insufficient_signal",
            ],
            "explicitly_not": [
                "a planner",
                "a scheduler",
                "an execution engine",
                "a sovereign decision surface",
                "a new mutable truth source",
            ],
        },
        "current_resumed_operation_readiness": {
            "meaning": "one bounded, non-executing verdict describing whether the current resumption candidate is fit to proceed under existing supervision surfaces.",
            "machine_surface": "sentientos.orchestration_intent_fabric.resolve_current_resumed_operation_readiness_verdict",
            "derived_from_existing_surfaces_only": [
                "resolve_current_orchestration_state",
                "resolve_current_orchestration_watchpoint",
                "resolve_watchpoint_satisfaction",
                "resolve_re_evaluation_trigger_recommendation",
                "resolve_current_orchestration_resumption_candidate",
                "derive_delegated_operation_readiness_verdict",
                "derive_packetization_gate",
                "resolve_active_handoff_packet_candidate",
                "next_move_proposal_visibility",
                "derive_operator_resolution_influence",
                "resolve_unified_orchestration_result",
            ],
            "values": [
                "ready_to_proceed",
                "proceed_with_caution",
                "hold_for_operator_review",
                "not_ready",
            ],
            "basis_flags": [
                "continuity_confidence",
                "stale_or_fragmented_wake_context",
                "unresolved_operator_influence",
                "missing_packet_or_proposal_continuity",
                "explicit_manual_review_hold",
            ],
            "explicitly_not": [
                "permission_to_execute",
                "scheduler behavior",
                "admission authority",
                "execution authority",
                "a sovereign orchestration layer",
            ],
        },
        "proposal_packet_continuity_review": {
            "meaning": "compact retrospective classifier indicating whether recent next-move proposals are converting into coherent active packet lineage or drifting through repeated holds/redirects/repacketization churn.",
            "machine_surface": "sentientos.orchestration_intent_fabric.derive_proposal_packet_continuity_review",
            "derived_from_existing_artifacts_only": [
                "orchestration_next_move_proposals.jsonl",
                "orchestration_handoff_packets.jsonl",
                "operator_action_briefs.jsonl",
                "operator_resolution_receipts.jsonl",
                "resolve_active_handoff_packet_candidate",
            ],
            "reads_fields": [
                "source_next_move_proposal_ref.proposal_id",
                "source_packetization_gate_ref.packetization_outcome",
                "packet_lineage.supersedes_handoff_packet_id",
                "packet_lineage.current_packet_candidate",
                "packet_lineage.refresh_reason",
                "resolution_kind",
            ],
            "values": [
                "coherent_proposal_packet_continuity",
                "hold_heavy_continuity",
                "redirect_heavy_continuity",
                "repacketization_churn",
                "fragmented_continuity",
                "insufficient_history",
            ],
            "summary_signals": [
                "stable_active_packet_usually_emerges",
                "continuity_signals.stabilized_into_one_active_packet",
                "continuity_signals.holds_materially_shaped_recent_path",
                "continuity_signals.redirects_materially_shaped_recent_path",
                "continuity_signals.repacketization_prevented_stable_continuity",
                "continuity_signals.lineage_fragmentation_present",
                "continuity_basis.*",
            ],
            "how_it_differs": {
                "from_unified_result_quality_review": "continuity review diagnoses proposal->packet lineage coherence before/alongside execution or fulfillment quality outcomes",
                "from_trust_confidence_posture": "trust posture synthesizes multiple review surfaces; continuity review is one bounded lineage-specific retrospective signal",
            },
            "explicitly_not": [
                "planner authority",
                "packetization gate override",
                "admission or execution control",
                "new venue routing or actuation",
            ],
        },
        "packetization_gating": {
            "meaning": "bounded constitutional gate deciding whether a next-move proposal can be packetized now, packetized with caution, or held for explicit reasons.",
            "machine_surface": "sentientos.orchestration_intent_fabric.derive_packetization_gate",
            "applies_only_to": [
                "next_move_proposal_to_handoff_packet_preparation",
                "handoff_packet_ready_vs_hold_marking",
            ],
            "derived_from_existing_signals_only": [
                "orchestration_trust_confidence_posture",
                "next_move_proposal",
                "next_move_proposal_review",
                "orchestration_operator_attention_recommendation",
                "next_move_proposal.operator_escalation_requirement_state",
            ],
            "outcomes": [
                "packetization_allowed",
                "packetization_allowed_with_caution",
                "packetization_hold_operator_review",
                "packetization_hold_insufficient_confidence",
                "packetization_hold_fragmentation",
                "packetization_hold_escalation_required",
            ],
            "how_it_differs": {
                "from_delegated_judgment": "delegated judgment recommends venue/posture; packetization gate only constrains packet staging readiness",
                "from_next_move_proposal": "proposal describes suggested next action; packetization gate decides if packaging that suggestion is presently permitted",
                "from_handoff_packet": "handoff packet carries staged payload; packetization gate is the bounded readiness/hold discipline embedded into that packet",
            },
            "explicitly_not": [
                "direct execution authority",
                "admission override",
                "venue recommendation override",
                "a sovereign planner",
            ],
        },
        "venues_still_staged_only": [
            "codex_implementation",
            "deep_research_audit",
            "operator_decision_required",
        ],
        "not_in_scope_yet": [
            "direct Codex invocation",
            "direct Deep Research invocation",
            "direct external adapter actuation",
            "direct browser/mouse/keyboard tool control",
            "external tool delegation with real execution authority",
        ],
    }
