from __future__ import annotations

from enum import Enum


class RequestType(str, Enum):
    TASK_EXECUTION = "TASK_EXECUTION"
    SPEECH_TTS = "SPEECH_TTS"
    AVATAR_EMISSION = "AVATAR_EMISSION"


class Decision(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"


class ReasonCode(str, Enum):
    OK = "OK"
    POLICY_DENY = "POLICY_DENY"
    RECURSION_BLOCKED = "RECURSION_BLOCKED"
    SELF_AUTH_FORBIDDEN = "SELF_AUTH_FORBIDDEN"
    UNKNOWN_REQUEST = "UNKNOWN_REQUEST"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    UNAUTHORIZED_REQUESTER = "UNAUTHORIZED_REQUESTER"
    POLICY_VERSION_MISMATCH = "POLICY_VERSION_MISMATCH"
    SCOPE_VIOLATION = "SCOPE_VIOLATION"
    HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
    MISSING_AUTHORIZATION = "MISSING_AUTHORIZATION"
    INVALID_AUTHORIZATION = "INVALID_AUTHORIZATION"
