enabled: true
mode: opportunistic_queued
max_rounds: 2
initiation:
  respond_first: true
  daily_quota: 8
  per_endpoint_quota: 3
  triggers:
    - low_confidence_high_impact
    - conflicting_sources
    - user_request
    - watchlist_topic
allowlist:
  - id: openai
    adapter: openai_live
    enabled: true
  - id: deepseek
    adapter: deepseek_live
    enabled: true
  - id: mistral
    adapter: mistral_live
    enabled: true
privacy:
  redact_secrets: true
  strip_pii: true
logging:
  jsonl_path: "logs/wdm/"
  include_raw: true
  include_summary: true
limits:
  per_turn_seconds: 20
  per_dialogue_seconds: 120
activation:
  default_mode: "respond_first"   # respond, then initiate on triggers
  cheers_enabled: true
  cheers_channel: "logs/wdm/cheers.jsonl"
adapters:
  openai:
    env_key: "OPENAI_API_KEY"
    model: "gpt-4o"   # editable
  deepseek:
    env_key: "DEEPSEEK_API_KEY"
    model: "deepseek-r1"
  mistral:
    env_key: "MISTRAL_API_KEY"
    model: "mistral-large"
redaction:
  patterns:
    - "sk-[A-Za-z0-9]{20,}"
    - "(?i)password\\s*[:=]\\s*\\S+"
    - "(?i)api[_-]?key\\s*[:=]\\s*\\S+"
