"""Codex helpers for SentientOS, exposed through lazy package exports."""
from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS: dict[str, tuple[str, str]] = {
    'AmendmentProposal': ('.amendments', 'AmendmentProposal'),
    'AmendmentReviewBoard': ('.amendments', 'AmendmentReviewBoard'),
    'IntegrityViolation': ('.amendments', 'IntegrityViolation'),
    'SpecAmender': ('.amendments', 'SpecAmender'),
    'WET_RUN_ENABLED': ('.config', 'WET_RUN_ENABLED'),
    'GapScanner': ('.autogenesis', 'GapScanner'),
    'LineageWriter': ('.autogenesis', 'LineageWriter'),
    'ReviewSymmetry': ('.autogenesis', 'ReviewSymmetry'),
    'SelfAmender': ('.autogenesis', 'SelfAmender'),
    'CoverageReader': ('.gap_seeker', 'CoverageReader'),
    'GapAmender': ('.gap_seeker', 'GapAmender'),
    'GapReporter': ('.gap_seeker', 'GapReporter'),
    'GapResolution': ('.gap_seeker', 'GapResolution'),
    'GapResolutionError': ('.gap_seeker', 'GapResolutionError'),
    'GapSeeker': ('.gap_seeker', 'GapSeeker'),
    'GapSignal': ('.gap_seeker', 'GapSignal'),
    'NarratorLink': ('.gap_seeker', 'NarratorLink'),
    'RepoScanner': ('.gap_seeker', 'RepoScanner'),
    'IntegrityDaemon': ('.integrity_daemon', 'IntegrityDaemon'),
    'Anomaly': ('.anomalies', 'Anomaly'),
    'AnomalyCoordinator': ('.anomalies', 'AnomalyCoordinator'),
    'AnomalyDetector': ('.anomalies', 'AnomalyDetector'),
    'AnomalyEmitter': ('.anomalies', 'AnomalyEmitter'),
    'ProposalPlan': ('.anomalies', 'ProposalPlan'),
    'RewriteProposalEngine': ('.anomalies', 'RewriteProposalEngine'),
    'EmbodimentEvent': ('.embodiment', 'EmbodimentEvent'),
    'EmbodimentMount': ('.embodiment', 'EmbodimentMount'),
    'BridgeState': ('.expression_bridge', 'BridgeState'),
    'CapabilityExpiredError': ('.expression_bridge', 'CapabilityExpiredError'),
    'CapabilityScopeError': ('.expression_bridge', 'CapabilityScopeError'),
    'EmissionCapability': ('.expression_bridge', 'EmissionCapability'),
    'ExpressionArtifact': ('.expression_bridge', 'ExpressionArtifact'),
    'ExpressionBridge': ('.expression_bridge', 'ExpressionBridge'),
    'ExpressionReplayError': ('.expression_bridge', 'ExpressionReplayError'),
    'ExpressionSchemaError': ('.expression_bridge', 'ExpressionSchemaError'),
    'FeedbackIngressForbidden': ('.expression_bridge', 'FeedbackIngressForbidden'),
    'PublishWindow': ('.expression_bridge', 'PublishWindow'),
    'PublishWindowClosedError': ('.expression_bridge', 'PublishWindowClosedError'),
    'CodexPlan': ('.plans', 'CodexPlan'),
    'PlanController': ('.plans', 'PlanController'),
    'PlanDashboard': ('.plans', 'PlanDashboard'),
    'PlanExecutor': ('.plans', 'PlanExecutor'),
    'PlanLedger': ('.plans', 'PlanLedger'),
    'PlanStep': ('.plans', 'PlanStep'),
    'PlanStorage': ('.plans', 'PlanStorage'),
    'Implementor': ('.implementations', 'Implementor'),
    'ImplementationBlock': ('.implementations', 'ImplementationBlock'),
    'ImplementationRecord': ('.implementations', 'ImplementationRecord'),
    'CodexMetaStrategy': ('.meta_strategies', 'CodexMetaStrategy'),
    'MetaStrategyStorage': ('.meta_strategies', 'MetaStrategyStorage'),
    'PatternMiningEngine': ('.meta_strategies', 'PatternMiningEngine'),
    'Refiner': ('.refinements', 'Refiner'),
    'RefinementTransform': ('.refinements', 'RefinementTransform'),
    'TestCycleManager': ('.testcycles', 'TestCycleManager'),
    'TestProposal': ('.testcycles', 'TestProposal'),
    'TestSynthesizer': ('.testcycles', 'TestSynthesizer'),
    'MetaStrategyGovernor': ('.governance', 'MetaStrategyGovernor'),
    'CodexNarrator': ('.narratives', 'CodexNarrator'),
    'IntentCandidate': ('.intent', 'IntentCandidate'),
    'IntentEmitter': ('.intent', 'IntentEmitter'),
    'IntentPrioritizer': ('.intent', 'IntentPrioritizer'),
    'PriorityScoringEngine': ('.intent', 'PriorityScoringEngine'),
    'PriorityWeights': ('.intent', 'PriorityWeights'),
    'ExpressionIntentBridgeError': ('.intent_drafts', 'ExpressionIntentBridgeError'),
    'ExpressionThresholdEvaluator': ('.intent_drafts', 'ExpressionThresholdEvaluator'),
    'IntentDraft': ('.intent_drafts', 'IntentDraft'),
    'IntentDraftLedger': ('.intent_drafts', 'IntentDraftLedger'),
    'ReadinessBand': ('.intent_drafts', 'ReadinessBand'),
    'LedgerInterface': ('.rewrites', 'LedgerInterface'),
    'PatchStorage': ('.rewrites', 'PatchStorage'),
    'RewriteDashboard': ('.rewrites', 'RewriteDashboard'),
    'RewritePatch': ('.rewrites', 'RewritePatch'),
    'ScopedRewriteEngine': ('.rewrites', 'ScopedRewriteEngine'),
    'CodexSandbox': ('.sandbox', 'CodexSandbox'),
    'SandboxViolation': ('.sandbox', 'SandboxViolation'),
    'StagedRecord': ('.sandbox', 'StagedRecord'),
    'ScaffoldEngine': ('.scaffolds', 'ScaffoldEngine'),
    'ScaffoldRecord': ('.scaffolds', 'ScaffoldRecord'),
    'StrategyOrchestrator': ('.orchestrator', 'StrategyOrchestrator'),
    'SpecEngine': ('.specs', 'SpecEngine'),
    'SpecProposal': ('.specs', 'SpecProposal'),
    'SpecReviewBoard': ('.specs', 'SpecReviewBoard'),
    'OutcomeEntry': ('.strategy', 'OutcomeEntry'),
    'StrategyAdjustmentEngine': ('.strategy', 'StrategyAdjustmentEngine'),
    'configure_strategy_root': ('.strategy', 'configure_strategy_root'),
    'strategy_engine': ('.strategy', 'strategy_engine'),
}

__all__ = [
    'AmendmentProposal',
    'AmendmentReviewBoard',
    'SpecAmender',
    'IntegrityViolation',
    'GapScanner',
    'LineageWriter',
    'ReviewSymmetry',
    'SelfAmender',
    'CoverageReader',
    'GapAmender',
    'GapReporter',
    'GapResolution',
    'GapResolutionError',
    'GapSeeker',
    'GapSignal',
    'NarratorLink',
    'RepoScanner',
    'IntegrityDaemon',
    'Anomaly',
    'AnomalyCoordinator',
    'AnomalyDetector',
    'AnomalyEmitter',
    'ProposalPlan',
    'RewriteProposalEngine',
    'EmbodimentEvent',
    'EmbodimentMount',
    'BridgeState',
    'CapabilityExpiredError',
    'CapabilityScopeError',
    'EmissionCapability',
    'ExpressionArtifact',
    'ExpressionBridge',
    'ExpressionReplayError',
    'ExpressionSchemaError',
    'FeedbackIngressForbidden',
    'CodexPlan',
    'PlanController',
    'PlanDashboard',
    'PlanExecutor',
    'PlanLedger',
    'PlanStep',
    'PlanStorage',
    'CodexMetaStrategy',
    'MetaStrategyStorage',
    'PatternMiningEngine',
    'MetaStrategyGovernor',
    'CodexNarrator',
    'ExpressionIntentBridgeError',
    'ExpressionThresholdEvaluator',
    'ExpressionArtifact',
    'ExpressionBridge',
    'FeedbackIngressForbidden',
    'IntentCandidate',
    'IntentDraft',
    'IntentDraftLedger',
    'IntentEmitter',
    'IntentPrioritizer',
    'PriorityScoringEngine',
    'PriorityWeights',
    'ReadinessBand',
    'LedgerInterface',
    'PatchStorage',
    'RewriteDashboard',
    'RewritePatch',
    'ScopedRewriteEngine',
    'CodexSandbox',
    'SandboxViolation',
    'StagedRecord',
    'WET_RUN_ENABLED',
    'StrategyOrchestrator',
    'SpecEngine',
    'SpecProposal',
    'SpecReviewBoard',
    'Implementor',
    'ImplementationBlock',
    'ImplementationRecord',
    'Refiner',
    'RefinementTransform',
    'PublishWindow',
    'PublishWindowClosedError',
    'TestCycleManager',
    'TestProposal',
    'TestSynthesizer',
    'ScaffoldEngine',
    'ScaffoldRecord',
    'OutcomeEntry',
    'StrategyAdjustmentEngine',
    'strategy_engine',
    'configure_strategy_root',
]

def __getattr__(name: str) -> Any:
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name, __name__), attribute)
    globals()[name] = value
    return value

def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
