name: Monthly Audit Ritual
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const month = new Date().toISOString().slice(0,7);
            const title = `Living Audit Ritual ${month}`;
            const body = `### Current Stewards\n- list names here\n\n### Checklist\n- [ ] Run \`python verify_audits.py\`\n- [ ] Review open PRs for banner compliance\n- [ ] Rotate steward if needed\n\nSee [AUDIT_LEDGER.md](../AUDIT_LEDGER.md) for previous results.`;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body
            });
