name: Federation Health Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Update federation health
        run: |
          python federation_health_badge.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update federation health'
          add: 'docs/FEDERATION_HEALTH.md'
