name: First PR Welcome

on:
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    if: github.event.pull_request.author_association == 'FIRST_TIMER'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = `Thanks for your first contribution! Please review the [Ritual Onboarding Checklist](../../blob/${{ github.event.pull_request.head.repo.full_name }}/docs/RITUAL_ONBOARDING.md).`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
