name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install build twine
      - run: python -m build
      - run: twine check dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
      - run: python scripts/generate_changelog.py > changelog.txt
      - uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to TestPyPI
        if: secrets.TEST_PYPI_TOKEN != ''
        run: twine upload -r testpypi --username __token__ --password ${{ secrets.TEST_PYPI_TOKEN }} dist/*
